### ISSUE TITLE
Numbers (Texts) not visible on iPhone simulators and real devices.

### ISSUE THREAD

**Issue by isaadabbasi** [bl00mber/react-phone-input-2#39]
Issue: Numbers (Texts) not visible on iPhone simulators and real devices.

Working on Android: Tested on Sony Xperia Z5. Xiaomi A1.
 Working on Web: Tested on Chrome 68.0.3440.106 (Official Build) (64-bit), Safari Version 11.1 (13605.1.33.1.2).
 **Not working**: Tested on iPhone (6, 6+, 7)

![image from ios 1](https://user-images.githubusercontent.com/15571610/44145760-53828ac8-a0a6-11e8-95d4-1b56e8ee8e7f.jpg)
![image from ios](https://user-images.githubusercontent.com/15571610/44145762-53dab22a-a0a6-11e8-913a-554d10a70b3c.jpg)

**Comment by DimaDK24** [comment]
[Demo](https://bl00mber.github.io/react-phone-input-2.html) works fine for me on iPhone 5S

**Comment by kashifsulaiman** [comment]
+1
In my case, using Moto E4 (Android), it's throwing error
`TypeError: "".padEnd is not a function`

**Comment by kashifsulaiman** [comment]
> +1
> In my case, using Moto E4 (Android), it's throwing error
> `TypeError: "".padEnd is not a function`

The above bug was different with the error mentioned in this issue.
The above bug is fixed and merged https://github.com/bl00mber/react-phone-input-2/pull/215
